### PR TITLE
Add optional image

### PR DESCRIPTION
**Pull request by otacke**
There have been multiple requests to add images to H5P.Accordion, e.g.:
* https://h5p.org/node/18392
* https://h5p.org/comment/11662#comment-11662
* https://h5p.org/node/62718

This pull request will allow to add images to accordions, either in addition to text or standalone. Images will scale to full width as usual in H5P. Translations have been updated and an update script to account for changes in semantics has been provided. Also, to allow CSS overrides by users, a wrapper with a style class has been used although there's nothing done.

Since the editor field properties of a library will not be set optional if the use of a library has been set to optional, the editor could be janky if users only want to have text or if they only want to have an image. To solve this problem, a H5P.Column-like approach was used which allows to add multiple content instances to a panel.

### CODE REVIEW

**Comment by falcon-git** [comment]
The plan is to add column or the upcoming layout as Accordion content panels.

**Comment by otacke** [comment]
That's good. Use https://github.com/h5p/h5p-accordion/pull/41 then ;-)

**Comment by profecarrie** [comment]
The comment thread regarding adding add image feature in Accordion H5P here and other places, is old yet there is still no Column feature in Accordion or another (simple!) solution for inserting an image in an embedded Content feature. 

Am I missing something? It is unbelievable that H5P cannot make this happen considering the whole platform is about interactive and technological activities.

**Comment by emmac123** [comment]
It is now 4 years since this issue was raised - yet I cannot see either columns or images in H5P accordions. Is this ever going to happen?

**Comment by nahalimedali** [comment]
Bonjour 
Avez vous trouvé une solution pour ajouter des images à l'accordéon ?
Merci

**Comment by otacke** [comment]
@nahalimedali That would be https://github.com/h5p/h5p-accordion/pull/41 - still untouched.

**Pull request closed without merging**
